# Generated by Django 6.0.3 on 2026-04-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('review_text', models.TextField()),
                ('client_image', models.ImageField(blank=True, upload_to='reviews/')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='organizations/')),
                ('website_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video directly (MP4, WebM)', upload_to='videos/files/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL (optional if uploading a file)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='videos/thumbnails/'),
        ),
    ]
