# Generated by Django 6.0.3 on 2026-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_clientreview_organization_video_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(help_text='Upload your CV/Resume (PDF)', upload_to='cv/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website_link',
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube channel or video link'),
        ),
    ]
