# Generated by Django 6.0.3 on 2026-04-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_sitesettings_email_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your profile photo for the hero section', upload_to='profile/'),
        ),
    ]
