# Generated by Django 6.0.3 on 2026-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_sitesettings_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Video Editing, Graphic Design', max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='video', help_text='Icon: video, image, calendar, camera, code, palette', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Expertise Areas',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_bio',
            field=models.TextField(default="I'm Shahzad Ahmad, a passionate video editor and graphic designer with over 5 years of experience. I specialize in creating high-quality visual content that helps brands stand out and connect with their audiences.", help_text='About section bio paragraph'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='Professional Video Editor & Graphic Designer crafting stunning visual experiences that captivate and inspire.', help_text='Tagline below name', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_line1',
            field=models.CharField(default='Shahzad', help_text='First line of name', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_line2',
            field=models.CharField(default='Ahmad', help_text='Second line of name', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_label',
            field=models.CharField(default='Years Experience', help_text='First stat label', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_value',
            field=models.CharField(default='5+', help_text='First stat value', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_label',
            field=models.CharField(default='Projects Completed', help_text='Second stat label', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_value',
            field=models.CharField(default='1000+', help_text='Second stat value', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('reels', 'Reels Editing'), ('podcast', 'Podcast Editing'), ('documentary', 'Documentary Editing')], default='reels', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo for hero section', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='With country code e.g. +923001234567', max_length=30),
        ),
    ]
